<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="keywords" content="EXAM"/>
        <meta name="description" content="Mann Island Finance Test"/>
        <meta name="author" content="Massimo Bianchi"/>
        <title>Mann Island Finance Test</title>
        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <style>
            table.center {
                margin-left:auto; 
                margin-right:auto;
            }
        </style>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->



    </head>
    <body>
        <img src="<?php echo $this->baseUrl("img/logo.png"); ?>">
        <br>
        <table class="center"> 
            <tr>
                <th>Companies</th>
                <th>Stock Quote</th>
                <th>Director</th>
            </tr>
            <tr>
                <td>
                    <select id="companies">
                        <option value="-1" disabled="disabled" selected="selected">Select</option>
                        <?php
                        foreach ($this->companies as $key => $value):
                            ?>
                            <option value="<?php echo $value->symbol ?>"><?php echo $value->name ?></option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                </td>
                <td>
                    <input type="text" id="quote" name="quote" value="" readonly="readonly">    
                </td>
                <td>
                    <input type="text" id="director" name="director" value="" readonly="readonly">    
                </td>
            </tr>
        </table>


        <!-- SHOW LAST FIVE RESULT -->

        <table class="table table-condensed">
            <caption style="font-weight:bold;">LAST FIVE RESULT</caption>
            <thead>
                <tr>
                    <th>Company</th>
                    <th>Stoke Quote</th>
                </tr>
            </thead>
            <tbody id="LastFive">
                <?php
                foreach ($this->lastFive as $key => $value):
                    ?>
                    <tr> 
                        <td><?php echo $value['companies']; ?></td>
                        <td><?php echo $value['quotes']; ?></td>
                    </tr>
                    <?php
                endforeach;
                ?>
            </tbody>
        </table>


        <!-- SHOW LAST FIVE RESULT -->


        <!-- MODAL WINDOW -->

        <div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">Error Occurred</h4>
                    </div>
                    <div class="modal-body">
                        <h3 id="error_message"></h3>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- END MODAL WINDOW -->



        <script>
            $(document).ready(function () {
                var companies = "";
                var quotes = "";
                $("#companies").change(function () {
                    companies = $("#companies option:selected").text();
                    $.get("<?php echo $this->url(array('controller' => 'index', 'action' => 'get-quote')); ?>", {symbol: this.value})
                            .done(function (data) {
                                if (data[0] == 0) {
                                    $("#quote").val(data[1]);
                                    //If Quotes ok store data on the DB
                                    $.get("<?php echo $this->url(array('controller' => 'index', 'action' => 'store-quotes')); ?>", {companies: companies, quotes: data[1]})
                                            .done(function (data) {
                                                $.get("<?php echo $this->url(array('controller' => 'index', 'action' => 'get-last-five')); ?>")
                                                        .done(function (data) {
                                                            updateTableLastFive(data);
                                                        });
                                            });
                                }
                                else {
                                    $("#error_message").html(data[1] + "<br>It is impossible to get the Quote");
                                    $('#basicModal').modal('toggle');
                                }

                            });
                    $.get("<?php echo $this->url(array('controller' => 'index', 'action' => 'get-directors-by-symbol')); ?>", {symbol: this.value})
                            .done(function (data) {
                                if (data[0] == 0)
                                    $("#director").val(data);
                                else {
                                    $("#error_message").html(data[1] + "<br>It is impossible to get the Director");
                                    $('#basicModal').modal('toggle');
                                }
                            });
                });
            });

            function updateTableLastFive(data)
            {
                $("#LastFive").html();
                var table = [];
                $.each(data, function (key, value) {
                    table.push("<tr><td>" + value.companies + "</td><td>" + value.quotes + "</td></tr>");
                });
                table = table.reverse();
                $("#LastFive").html(table);
            }

        </script>
        <script src="js/bootstrap.min.js"></script>    
    </body>
</html>